### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by lingchuanzhou** [SeldonIO/seldon-core#4887]
## Describe the bug

`=============================
== Triton Inference Server ==
=============================

NVIDIA Release 23.02 (build 53616260)
Triton Server Version 2.31.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

Warning: '--strict-model-config' has been deprecated! Please use '--disable-auto-complete-config' instead.
W0605 06:26:38.147148 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not bble: CUDA driver version is insufficient for CUDA runtime version
I0605 06:26:38.147242 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
E0605 06:26:38.150360 1 model_repository_manager.cc:1004] Poll failed for model directory '1': Invalid model name: Could notne backend for model '1' with no backend in model configuration. Expected model name of the form 'model.<backend_name>'.
I0605 06:26:38.150393 1 server.cc:563]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0605 06:26:38.150403 1 server.cc:590]
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I0605 06:26:38.150413 1 server.cc:633]
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I0605 06:26:38.150671 1 metrics.cc:757] Collecting CPU metrics
I0605 06:26:38.150783 1 tritonserver.cc:2264]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                        |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                       |
| server_version                   | 2.31.0                                                                                                                                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_pdel_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
| model_repository_path[0]         | /mnt/models                                                                                                                                                                                  |
| model_control_mode               | MODE_NONE                                                                                                                                                                                    |
| strict_model_config              | 0                                                                                                                                                                              `

## To reproduce

`apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: liqi
  namespace: seldon
spec:
  name: resnet32
  predictors:
  - graph:
      implementation: TRITON_SERVER
      modelUri: s3://alluxio/s3b/liqi_model/planmodel
      envSecretRefName: seldon-init-container-secret
      name: planmodel
      type: MODEL
    name: liqi
    replicas: 1
  protocol: v2
`
## Expected behaviour

expecte mode load success!

## Environment
kubernetes 1.23, one node with Nvidia Tesla T4

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by sakoush** [comment]
It looks like that you might need to install / update nvidia drivers in your kubernetes cluster given the warning in your stacktrace.

Follow this [link](https://github.com/NVIDIA/k8s-device-plugin) for more info.

**Comment by cliveseldon** [comment]
Closing for now - please comment if still an issue

**Comment by WaterKnight1998** [comment]
@lingchuanzhou I am finding the same error, and same triton server is working in other server without seldon.

**Comment by WaterKnight1998** [comment]
I fixed by using the next conf:

```yaml
---
apiVersion: mlops.seldon.io/v1alpha1
kind: ServerConfig
metadata:
  name: triton
  namespace: seldon-mesh
spec:
  podSpec:
    terminationGracePeriodSeconds: 120
    serviceAccountName: seldon-server
    containers:
    - image: docker.io/seldonio/seldon-rclone:2.6.0
      imagePullPolicy: IfNotPresent
      name: rclone
      ports:
      - containerPort: 5572
        name: rclone
        protocol: TCP
      lifecycle:
        preStop:
          httpGet:
            port: 9007
            path: terminate
      resources:
        requests:
          cpu: "200m"
          memory: '100M'
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        tcpSocket:
          port: 5572
        timeoutSeconds: 1
      volumeMounts:
      - mountPath: /mnt/agent
        name: triton-models
    - image: docker.io/seldonio/seldon-agent:2.6.0
      imagePullPolicy: IfNotPresent
      name: agent
      command:
        - /bin/agent
      args:
        - --tracing-config-path=/mnt/tracing/tracing.json 
      env:
      - name: SELDON_SERVER_CAPABILITIES
        value: "triton,dali,fil,onnx,openvino,python,pytorch,tensorflow,tensorrt"
      - name: SELDON_OVERCOMMIT_PERCENTAGE
        value: "10"
      - name: SELDON_MODEL_INFERENCE_LAG_THRESHOLD
        value: "30"
      - name: SELDON_MODEL_INACTIVE_SECONDS_THRESHOLD
        value: "600"
      - name: SELDON_SCALING_STATS_PERIOD_SECONDS
        value: "20"
      - name: SELDON_SERVER_HTTP_PORT
        value: "9000"
      - name: SELDON_SERVER_GRPC_PORT
        value: "9500"
      - name: SELDON_REVERSE_PROXY_HTTP_PORT
        value: "9001"
      - name: SELDON_REVERSE_PROXY_GRPC_PORT
        value: "9501"          
      - name: AGENT_TLS_SECRET_NAME
        value: ""
      - name: AGENT_TLS_FOLDER_PATH
        value: ""
      - name: SELDON_SCHEDULER_HOST
        value: "seldon-scheduler"
      - name: SELDON_SCHEDULER_PORT
        value: "9005"
      - name: SELDON_METRICS_PORT
        value: "9006"
      - name: SELDON_DRAINER_PORT
        value: "9007"
      - name: SELDON_SERVER_TYPE
        value: "triton"
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MEMORY_REQUEST
        valueFrom:
          resourceFieldRef:
            containerName: triton
            resource: requests.memory
      ports:
      - containerPort: 9501
        name: grpc
        protocol: TCP
      - containerPort: 9001
        name: http
        protocol: TCP
      - containerPort: 9006
        name: metrics
        protocol: TCP
      lifecycle:
        preStop:
          httpGet:
            port: 9007
            path: terminate
      resources:
        requests:
          cpu: "500m"
          memory: '500M'
      volumeMounts:
      - mountPath: /mnt/agent
        name: triton-models
      - name: config-volume
        mountPath: /mnt/config
      - name: tracing-config-volume
        mountPath: /mnt/tracing
    - image: nvcr.io/nvidia/tritonserver:23.07-py3
      command:
        - "sh"
        - "-c"
        - "tritonserver --model-repository=$(SERVER_MODELS_DIR) --http-port=$(SERVER_HTTP_PORT) --grpc-port=$(SERVER_GRPC_PORT) --log-verbose=1 --model-control-mode=explicit --backend-config=python,shm-default-byte-size=16777216"
      imagePullPolicy: IfNotPresent
      env:
      - name: SERVER_HTTP_PORT
        value: "9000"
      - name: SERVER_GRPC_PORT
        value: "9500"
      - name: SERVER_MODELS_DIR
        value: "/mnt/agent/models"
      - name: LD_PRELOAD
        value: /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4
      resources:
        requests:
          cpu: 1
          memory: '1G'
      livenessProbe:
        httpGet:
          path: /v2/health/live
          port: server-http
      readinessProbe:
        httpGet:
          path: /v2/health/live
          port: server-http
        initialDelaySeconds: 5
        periodSeconds: 5          
      startupProbe:
        httpGet:
          path: /v2/health/live
          port: server-http
        failureThreshold: 10
        periodSeconds: 10
      name: triton
      ports:
      - containerPort: 9500
        name: server-grpc
        protocol: TCP
      - containerPort: 9000
        name: server-http
        protocol: TCP
      - containerPort: 8002
        name: server-metrics
      lifecycle:
        preStop:
          httpGet:
            port: 9007
            path: terminate
      volumeMounts:
      - mountPath: /mnt/agent
        name: triton-models
        readOnly: true
      - mountPath: /dev/shm
        name: dshm
        readOnly: false
    securityContext:
      fsGroup: 2000
      runAsUser: 1000
      runAsNonRoot: true
    volumes:
    - name: config-volume
      configMap:
        name: seldon-agent
    - name: tracing-config-volume
      configMap:
        name: seldon-tracing
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "256Mi"
  volumeClaimTemplates:
  - name: triton-models
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

```
